name: CICD_using_aws_ec2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Code Clean
        run: mvn clean

      - name: Code Validate
        run: mvn validate

      - name: Code Build
        run: mvn compile

      - name: Code Test
        run: mvn test

      - name: Code Package
        run: mvn package

      - name: Save JAR Artifact
        run: mkdir -p artifacts && cp target/*.jar artifacts/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/Cab:v1

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Install & Pull Image from Docker Hub
        run: |
          sudo apt install docker.io -y
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/Cab:v1
          
      - name: Delete Old Container
        run: sudo docker rm -f Cab || true

      - name: Run Docker Image
        run: sudo docker run -d -p 8080:8080 --name Cab ${{ secrets.DOCKERHUB_USERNAME }}/Cab:v1
